
<?php

//so gets some things working
function makemynode_node_view_alter(&$build){


    // $node= node_load(2);
    // $title=$node->title;
    // print "<pre>";
    // print_r($node);
    // print "</pre>";

    print "<pre>";
    print_r($build['body']['#object']->nid);
    print "</pre>";

// $page = 'page';
// $nodes = node_load_multiple(array(), array('type' => $page));
//   print "<pre>";
//   print_r( $nodes);
//   print "</pre>";
// foreach($nodes as $page) {
//         print $page->nid;
//         print $page->title;
//     }
}
